security:
  oauth2:
    client:
      clientId: <consumer key>
      clientSecret: <consumer secret>
      accessTokenUri: https://login.salesforce.com/services/oauth2/token
      userAuthorizationUri: https://login.salesforce.com/services/oauth2/authorize
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://login.salesforce.com/services/oauth2/userinfo
      preferTokenInfo: false